import os

###############################################################################
###############################################################################
# Meta information
###############################################################################
DATA_ROOT = "../data"
RAW_DATA_ROOT = os.path.join(DATA_ROOT, "raw_data")
INTERMEDIATE_DATA_ROOT = os.path.join(DATA_ROOT, "intermediate_files")
OUTPUT_DATA_ROOT = os.path.join(DATA_ROOT, "output")

###############################################################################
###############################################################################
###############################################################################
# Workflow
###############################################################################

###############################################################################
# Cleaning
NEWSGUARD_DATA_FILE = os.path.join(RAW_DATA_ROOT, "newsguard_20200519.csv")
NEWSGUARD_CLEANED_DATA_FILE = os.path.join(INTERMEDIATE_DATA_ROOT, "newsguard_cleaned.csv")

rule clean_newsguard:
    input: NEWSGUARD_DATA_FILE
    params: "newsguard"
    output: NEWSGUARD_CLEANED_DATA_FILE
    shell: "python clean_newsguard.py {input} {params} {output}"


MBFC_DATA_FILE = os.path.join(RAW_DATA_ROOT, "mbfc_ratings.csv")
MBFC_CLEANED_DATA_FILE = os.path.join(INTERMEDIATE_DATA_ROOT, "mbfc_cleaned.csv")

rule clean_mbfc:
    input: MBFC_DATA_FILE
    params: "mbfc"
    output: MBFC_CLEANED_DATA_FILE
    shell: "python clean_mbfc.py {input} {params} {output}"


ROBERTSON_DOMAINS_FILE = os.path.join(RAW_DATA_ROOT, "robertson_domains.tsv")
ROBERTSON_CLEANED_DOMAINS_FILE = os.path.join(
    INTERMEDIATE_DATA_ROOT, "robertson_cleaned.csv"
)

rule clean_robertson:
    input: ROBERTSON_DOMAINS_FILE
    params: "robertson"
    output: ROBERTSON_CLEANED_DOMAINS_FILE
    shell: "python clean_robertson.py {input} {params} {output}"

HOHENBERG_DATA_FILE = os.path.join(RAW_DATA_ROOT, "hohenberg.csv")
HOHENBERG_CLEANED_DATA_FILE = os.path.join(INTERMEDIATE_DATA_ROOT, "hohenberg_cleaned.csv")

rule clean_hohenberg:
    input: HOHENBERG_DATA_FILE
    params: "hohenberg"
    output: HOHENBERG_CLEANED_DATA_FILE
    shell: "python clean_hohenberg.py {input} {params} {output}"


LE_QUERE_DATA_FILE = os.path.join(RAW_DATA_ROOT, "le_quere.csv")
LE_QUERE_CLEANED_DATA_FILE = os.path.join(INTERMEDIATE_DATA_ROOT, "le_quere_cleaned.csv")

rule clean_le_quere:
    input: LE_QUERE_DATA_FILE
    output: LE_QUERE_CLEANED_DATA_FILE
    shell: "python clean_le_quere.py {input} {output}"

FISHER_DATA_FILE = os.path.join(RAW_DATA_ROOT, "fisher.csv")
FISHER_CLEANED_DATA_FILE = os.path.join(INTERMEDIATE_DATA_ROOT, "fisher_cleaned.csv")

rule clean_fisher:
    input: FISHER_DATA_FILE
    output: FISHER_CLEANED_DATA_FILE
    shell: "python clean_fisher.py {input} {output}"

HORNE_DATA_FILE = os.path.join(RAW_DATA_ROOT, "horne.csv")
HORNE_CLEANED_DATA_FILE = os.path.join(INTERMEDIATE_DATA_ROOT, "horne_cleaned.csv")

rule clean_horne:
    input: HORNE_DATA_FILE
    output: HORNE_CLEANED_DATA_FILE
    shell: "python clean_horne.py {input} {output}"

ABYZ_DATA_FILE = os.path.join(RAW_DATA_ROOT, "abyz.csv")
ABYZ_CLEANED_DATA_FILE = os.path.join(INTERMEDIATE_DATA_ROOT, "abyz_cleaned.csv")

rule clean_abyz:
    input: ABYZ_DATA_FILE
    output: ABYZ_CLEANED_DATA_FILE
    shell: "python clean_abyz.py {input} {output}"


###############################################################################
# Aggregation
CLEANED_COMBINED_DATA_FILE = os.path.join(INTERMEDIATE_DATA_ROOT, "cleaned_combined.csv")

rule combine_cleaned_data:
    input:
        NEWSGUARD_CLEANED_DATA_FILE,
        MBFC_CLEANED_DATA_FILE,
        ROBERTSON_CLEANED_DOMAINS_FILE,
        HOHENBERG_CLEANED_DATA_FILE,
        LE_QUERE_CLEANED_DATA_FILE,
        FISHER_CLEANED_DATA_FILE,
        HORNE_CLEANED_DATA_FILE,
        ABYZ_CLEANED_DATA_FILE
    output: CLEANED_COMBINED_DATA_FILE
    shell: "python concat_csv.py {input} {output}"
